"""add project period category highlights paper url

Revision ID: 0002
Revises: 0001
Create Date: 2026-10-08 18:10:43.724395

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0002"
down_revision: str | Sequence[str] | None = "0001"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("projects", sa.Column("period", sa.String(length=40), nullable=True))
    op.add_column("projects", sa.Column("category", sa.String(length=80), nullable=True))
    # server_default lets the column be added to tables that already contain projects.
    op.add_column(
        "projects",
        sa.Column(
            "highlights",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
            server_default=sa.text("'[]'"),
        ),
    )
    op.add_column("projects", sa.Column("paper_url", sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("projects", "paper_url")
    op.drop_column("projects", "highlights")
    op.drop_column("projects", "category")
    op.drop_column("projects", "period")
    # ### end Alembic commands ###
