"""add project visual

Revision ID: 0003
Revises: 0002
Create Date: 2026-10-08 19:13:49.571493

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0003"
down_revision: str | Sequence[str] | None = "0002"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "projects", sa.Column("visual", sa.String(length=20), server_default="network", nullable=False)
    )
    op.create_check_constraint(
        "ck_projects_visual",
        "projects",
        "visual IN ('agents', 'pipeline', 'services', 'vectors', 'lowrank', 'app', 'network')",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("ck_projects_visual", "projects", type_="check")
    op.drop_column("projects", "visual")
    # ### end Alembic commands ###
